name: api_practice
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.9.0







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1
  build_runner: ^2.8.0

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
